import Page_container from "./Page_sup/Page_container";

export const metadata = {
  title: "RDAPP",
  description: "RDAPP is an innovative platform that streamlines research and development processes while ensuring compliance with the Saudi Building Code (SBC) for each project. It tracks project progress stages, facilitating seamless coordination among all parties from project reception through initial risk assessment and expert reviews in geotechnical studies, structural analysis, and innovative materials. The app efficiently manages each technical inspection stage on-site. By centralizing information, automating workflows, and enhancing communication, RDAPP boosts productivity while employing advanced encryption and security measures to protect sensitive data, making it a trusted solution for organizations focused on innovation.",
  keywords:[
    "app",
    "RD",
    "dating apps",
    "apple watch series 8",
    "qr code scanner",
    "tinder app",
    "apple iphone 14",
    "google play store",
    "play store app",
    "free dating apps",
    "apple watch 7",
    "play store download",
    "android",
    "whatsapp api",
    "google play store app",
    "hinge dating",
    "amazon kindle",
    "apple watches",
    "smart switch",
    "phone tracker",
    "apple 14 pro",
    "tiktok app",
    "google play store download",
    "play store app download",
    "track my phone",
    "google play card",
    "google play gift card",
    "apple ultra watch",
    "photoshop app",
    "shein app",
    "play store app install",
    "apple wallet",
    "free video chat",
    "smart switch app",
    "tik tok app",
    "google app store",
    "booking com app",
    "google play app",
    "play store install",
    "latest apple watch",
    "pdf scanner",
    "apple smart watch",
    "apple watch series 4",
    "itunes card",
    "capcut video editor",
    "iphone 14 apple",
    "ludo king",
    "apple tracker",
    "google camera",
    "apple watch price",
    "wifi analyzer",
    "google play store app install",
    "pic collage",
    "google play store app download for android",
    "tinder gold",
    "chromecast app",
    "google play store app download",
    "play store app download and install",
    "galaxy store",
    "play store download for pc",
    "apple watch series",
    "netflix app",
    "play store download app install",
    "adobe photoshop express",
    "video maker app",
    "bigolive",
    "itunes store",
    "apple car play",
    "music player",
    "call recorder",
    "universal tv remote",
    "apple homekit",
    "chat alternative",
    "apple watch faces",
    "google mobile",
    "samsung tv plus",
    "game app",
    "shopee app",
    "play store app install free download",
    "photolab",
    "samsung galaxy store",
    "whatsapp tracker",
    "instagram followers app",
    "music download app",
    "amazon mobile",
    "call recording app",
    "play store com",
    "mobile legends bang bang",
    "play store download free",
    "cybersecurity risk assessment",
    "security risk assessment",
    "vendor risk assessment",
    "ibook",
    "third party risk assessment",
    "ludo download",
    "health and safety risk assessment",
    "risk assessment tool",
    "beauty camera",
    "play store official",
    "talking tom",
    "english language proficiency test",
    "play store play store",
    "fire safety risk assessment",
    "photogrid",
    "risk assessment cybersecurity",
    "tik tok lite",
    "vidmate youtube",
    "dji go 4",
    "iso 27001 risk assessment",
    "dji mimo",
    "servicenow vendor risk management",
    "mi remote",
    "wearfit pro",
    "construction risk assessment",
    "cambridge english placement test",
    "google play market",
    "risk assessment cybersecurity example",
    "business risk assessment",
    "zepp life",
    "poppy playtime chapter 1",
    "cloud risk assessment",
    "cambridge english test online",
    "risk legacy",
    "cyber risk assessment framework",
    "xmeye",
    "play spotify",
    "cybersecurity risk assessment framework",
    "lord of the rings risk",
    "data risk assessment",
    "oxford online placement test",
    "risk analysis cyber security",
    "privacy risk assessment",
    "risk assessment services",
    "cybersecurity risk analysis",
    "supplier financial risk assessment",
    "network risk assessment",
    "third party assessment",
    "threat risk assessment",
    "warehouse risk assessment",
    "risk assessment for cyber security",
    "risk europe",
    "risk assessment for construction site",
    "cambridge reading test",
    "cybersecurity risk register",
    "automated risk assessment",
    "building risk assessment",
    "data privacy risk assessment",
    "written assignment",
    "risk analysis in cyber security",
    "identifying hazards in the workplace",
    "quality and risk management",
    "aml assessment",
    "business continuity risk assessment",
    "cubiksonline",
    "threat and risk assessment",
    "design risk assessment",
    "quantitative risk assessment example",
    "data assessment",
    "risk assessment in construction industry",
    "risk assessment solutions",
    "risk assessment test",
    "network security risk assessment",
    "risk management definition and examples",
    "cloud computing risk assessment",
    "financial risk assessment example",
    "security risk analysis in cyber security",
    "risk rules",
    "business continuity assessment",
    "hse coshh assessment",
    "risk management audit",
    "medical device risk assessment",
    "risk board",
    "risk boardgame",
    "manual handling risk assessment example",
    "dream league soccer 2020",
    "risk analysis framework",
    "comprehensive risk assessment",
    "risk identification in construction projects",
    "risk assessment ppt",
    "risk analysis example for project",
    "strategic risk assessment",
    "fraud risk assessment acfe",
    "grc assessment",
    "fraud assessment",
    "geopolitical risk analysis",
    "finance department risk assessment",
    "facility risk assessment example",
    "hazard identification and risk assessment procedure",
    "simops risk assessment",
    "qualitative risk analysis in project management",
    "corruption risk management",
    "control hazard and risk",
    "cramm risk assessment",
    "iosh risk assessment project",
    "iso 45001 hazard definition",
    "play google com",
    "top soil",
    "autocad architecture",
    "peat moss",
    "midcentury modern",
    "seed starting mix",
    "loam soil",
    "bonsai soil",
    "organic soil",
    "humus",
    "happy frog soil",
    "rockwool cubes",
    "perlite soil",
    "fox farm ocean forest",
    "living soil",
    "super soil",
    "happy frog potting soil",
    "soil for plants",
    "coco peat",
    "3d home architect",
    "plant soil",
    "architectural designs house plans",
    "coarse vermiculite",
    "humichar",
    "peat moss soil",
    "barcelona gaudi",
    "coco soil",
    "sphagnum peat moss",
    "buy soil",
    "certified risk manager",
    "chief architect home designer",
    "peat pellets",
    "soil for garden",
    "buy soil near me",
    "green manure seeds",
    "bonsai soil mix",
    "pond soil",
    "certified risk management professional",
    "jiffy peat pellets",
    "perlite for plants",
    "cad architecture",
    "supply chain cyber security",
    "security and risk management",
    "garden soil for sale near me",
    "ai risk management",
    "small house interior design",
    "soil meter",
    "mid century modern style",
    "enterprise risk management system",
    "best garden soil",
    "coco peat soil",
    "vermiculite soil",
    "garden mix soil",
    "atlas of brutalist architecture",
    "soil activator",
    "clay soil for sale",
    "rose soil",
    "sunshine mix 4",
    "black cow compost",
    "sap risk management",
    "modern house interior",
    "vectorworks architect",
    "modern house interior design",
    "enterprise risk management solutions",
    "hydroponic growing medium",
    "plants for clay soil",
    "microbiometer",
    "seed soil",
    "credit risk analytics",
    "clay dirt",
    "soil for plants near me",
    "plant dirt",
    "risk management in financial institutions",
    "building design drawing",
    "liquidity risk management in banks",
    "tropical soil",
    "building plans and designs",
    "amazon soil",
    "risk management plan for construction project",
    "it risk management policy",
    "coco peat price",
    "three way meter",
    "bungalow style house",
    "credit risk management framework",
    "enterprise risk consulting",
    "black kow cow manure",
    "sandy clay",
    "introduction to architecture",
    "human body structure",
    "enterprise risk management ppt",
    "cyber supply chain",
    "sterile soil",
    "small modern house interior design",
    "francis dk ching",
    "soil for potatoes",
    "calathea soil",
    "human bone structure",
    "bungalow style homes",
    "iso 31000 2018 risk management",
    "bamboo soil",
    "edible soil",
    "urban design architecture",
    "black soil for plants",
    "vermicast soil",
    "hoya soil",
    "soilless agriculture",
    "plants that grow well in clay soil",
    "best soil for planting",
    "modern bungalow designs",
    "soil pot",
    "francis ching",
    "alkaline plants",
    "human structure",
    "minimalist house interior design",
    "limestone soil",
    "arch design for home entrance",
    "backbone structure",
    "fixed income securities valuation risk and risk management",
    "hand structure",
    "light soil",
    "lucky bamboo in soil",
    "postmodern interior design",
    "safety management ppt",
    "ai data management",
    "big data for dummies",
    "edureka big data",
    "ai & big data",
    "latest big data technologies",
    "big data analytics methods",
    "big data analytics python",
    "big data fintech"
  ]
  
};


export default function Page() {
  return (
    <>
      <Page_container />
    </>
  );
}
