import { Suspense } from "react";
import Loading from "./loading";
import dynamic from "next/dynamic";
const Page_container = dynamic(() => import("./Page_sup/Page_container"), {
  ssr: false,
});

export const metadata = {
  title: "BONDIFY CRM",
  description:
    "bondify CRM is a comprehensive platform that streamlines customer engagement and business operations. It offers tools for managing leads, tasks, and projects, while optimizing sales pipelines. bondify CRM also simplifies payments and quotations, allowing businesses to handle invoicing and quotes effortlessly. With seamless integration to calendars and email, it helps boost efficiency and improve client relationships.",
  keywords:[
    "bondify crm", "bondify", "crm apps", "crm applications", "crm company", 
    "software for business", "business application", "contact management systems", 
    "customized crm", "crm customer", "crm for services", "tool crm", "crm sw", 
    "creating crm", "crm software is", "custom software applications", "crm saudi", 
    "application custom", "crm ksa", "crm software", "crm system", "free crm", 
    "hubspot crm", "best crm for small business", "monday crm", "best crm", 
    "free crm for small business", "crm tools", "crm for small business", 
    "free crm software", "pipeline crm", "pipedrive crm", "real estate crm", 
    "crm platforms", "sales crm", "google crm", "best free crm", "simple crm", 
    "crm programs", "hubspot free crm", "open source crm", "customer management system", 
    "pipedrive pricing", "lead management system", "zendesk crm", "salesforce demo", 
    "simple crm for small business", "freshsales crm", "crm online", "best crm systems", 
    "hubspot crm pricing", "free crm software for small business", "free crm tools", 
    "crm marketing", "cheap crm", "top crm software", "monday crm pricing", "online crm", 
    "crm solutions", "best sales crm", "salesforce crm pricing", "free crm system", 
    "octopus crm", "odoo crm", "cheap crm for small business", "customer success platform", 
    "basic crm", "close crm", "customer relationship management software", "free sales crm", 
    "crm monday", "bitrix24 crm", "top crm", "personal crm", "salesforce financial services cloud", 
    "oracle netsuite crm", "best crm tools", "customer relationship management system", 
    "kommo crm", "hipaa compliant crm", "sales software for small business", "crm for startups", 
    "top 10 crm software", "call center crm", "white label crm", "free crm for startups", 
    "clickup crm", "crm services", "free online crm", "crm customer relationship management", 
    "crm cloud", "asana crm", "google workspace crm", "crm companies", 
    "crm tools for small business", "contact management system", "free client management software", 
    "b2b crm", "custom crm", "lead management software", "healthcare crm", "zoho software", 
    "crm saas", "crm management software", "creatio crm", "crm excel", "best crm platforms", 
    "crm automation", "crm for accountants", "crm lead management", "all in one crm", 
    "salesforce pricing small business", "top crm systems", "microsoft crm 365", "crm pricing", 
    "project management crm", "top 10 crm", "customer management", "freshsales pricing", 
    "hr crm", "customer crm", "pipe crm", "salesflare", "freshsales suite", 
    "crm and project management", "salesforce crm software", "cloud based crm", "the best crm", 
    "trello crm", "sales management software", "crm free open source", "thrive crm", 
    "linkedin crm", "mondaycrm", "popular crm", "crm software list", "crm providers", 
    "crm ticketing system", "pipedrive plans", "relationship management software", 
    "popular crm systems", "crm system software", "customer service crm", 
    "crm and project management software", "top 50 crm software", "fresh sales crm", 
    "crm freeware", "most popular crm", "crm tools list", "crm packages", 
    "customer relationship management tools", "social crm", "partner relationship management software", 
    "crm download", "top crm tools", "mobile crm", "free crm software download", 
    "crm software companies", "automotive crm", "salesforce crm tool", "open source crm software", 
    "best crm for shopify", "microsoft crm system", "headless crm", "best open source crm", 
    "salesforce crm features", "zoho free", "zoho crm demo", "top crm platforms", 
    "best crm solutions", "salesforce tool", "zoho demo", "crm 365", "crm software microsoft", 
    "microsoft dynamics crm pricing", "crm cost", "customer relationship software", 
    "financial services crm", "crm comparisons", "call center crm software", "online crm system", 
    "crm consulting", "top 5 crm", "customer management tools", "workday crm", 
    "zoho call center", "rise crm", "sales crm system", "erp crm software", 
    "microsoft dynamics sales", "laravel crm", "crm sistem", "crm client relationship management", 
    "hospitality crm", "crm and marketing automation", "sharepoint crm", "logistics crm", 
    "microsoft crm tool", "microsoft crm pricing", "dynamics 365 partners", 
    "pipedrive marketplace", "microsoft teams crm", "crm clickup", "crm tools for marketing", 
    "crm contact center", "crm software price", "cloud based crm software", 
    "digital marketing crm", "crm tracking", "zoho sales crm", "zoho phonebridge", 
    "dynamics crm pricing", "odoo crm pricing", "azure crm", "dynamics 365 ce", "telecrm", 
    "crm and marketing", "customer segmentation software", "linkedin salesforce integration", 
    "crm project", "office crm", "php crm", "octopuscrm", "zoho sales", 
    "pipedrive scheduler", "crm modules", "zoho crm integration", "pipedrive real estate", 
    "crm windows", "finance crm", "crm expert", "crm reporting", "pipedrive crm demo", 
    "customer relationship management in marketing", "customer relationship management platform", 
    "crm partners", "crm accounting software", "microsoft dynamics customer service", 
    "crm cms", "dynamics 365 customer service enterprise", "crm contact", 
    "crm development company", "zoho implementation partner", "digital crm", 
    "microsoft dynamics 365 download", "customer relationship management database", 
    "crm kpis", "erp and crm software", "typeform hubspot", "zoho implementation", 
    "helloleads", "3cx crm", "zoho reseller", "crm planning", "crm explained", 
    "salesforce open source", "crm data analysis", "sap crm modules", "crm loyalty", 
    "crm flow", "sales management crm", "customer retention management software", 
    "crm cx", "onyx crm", "erpnext crm", "crm on demand", "social customer relationship management", 
    "crm and cms", "customer relationship management solutions", "crm full", "crm supply chain", 
    "customer relationship management in supply chain management", "crm in supply chain management", 
    "success software", "ice crm", "suitecrm installation", "marketing with salesforce", 
    "mobilecrm", "customer experience management strategy", "customer relationship management project", 
    "crm codecanyon", "campaign management in crm", "scm crm", "zoho docs download", 
    "customer relationship management crm software", "project management software", 
    "microsoft project", "square reader", "square credit card reader", "ms project", 
    "best project management software", "inspirational quotes", "construction management software", 
    "motivational quotes", "card payment machine", "task management software", "flexepin", 
    "positive quotes", "quote of the day", "microsoft project management", "quotes about life", 
    "buy paysafecard online", "construction project management software", "project tracker", 
    "clover flex", "construction scheduling software", "good morning quotes", 
    "project tracking software", "project planning software", "words of encouragement", 
    "neosurf voucher", "love quotes", "construction project management", "encouraging quotes", 
    "best construction management software", "pmbok", "pmp boot camp", "paypal prepaid", 
    "microsoft project management software", "virtual visa card", "project management platforms", 
    "project scheduling software", "bible quotes", "inspirational bible verses", "project software", 
    "powerful motivational quotes", "google pay card", "top project management software", 
    "best construction project management software", "inspirational quotes for women", 
    "pay safe card", "short inspirational quotes", "leadership quotes", "kitchen quotes", 
    "friendship quotes", "motivational quotes for success", "jira alternative", 
    "inspirational quotes about life", "inspirational quotes for work", "motivational quotes for work", 
    "team task management", "love quotes for her", "project tracking tools", "construction management app", 
    "teamwork project management", "uplifting quotes", "quote of the day for work", "inspirational words", 
    "project time tracking", "self love quotes", "love quotes for him", "success quotes", 
    "project management website", "words of wisdom", "best construction software", 
    "motivational words", "microsoft project plan", "happiness quotes", 
    "online project management software", "daily motivational quotes", "pay safe", "daily quotes", 
    "to do list software", "paypal prepaid mastercard", "ms project software", 
    "top 10 project management software", "daily inspirational quotes", "team task management app", 
    "simple project management", "graduation quotes", "anniversary quotes", 
    "microsoft project cost", "project planning tool", "good quotes", "construction software", 
    "clover pos", "best project tracking software", "project scheduling", "best project management tools", 
    "to do app", "team management app", "construction management software for small business", 
    "management quotes", "buy visa card", "top 10 project management tools", "funny quotes", 
    "team project management", "buy google play gift card", "funny quotes about life", 
    "project management tool", "square chip reader", "visa gift card online", "monday.com", 
    "leadership quotes for work", "team management software", "agile project management tools", 
    "top construction project management software", "square online", "bible verses for strength", 
    "bible verses about strength", "good team quotes", "app for tasks", "project tracking app", 
    "team time tracking", "buy itunes gift card", "project manager tools", "sims 4 motivational quotes", 
    "easy project management", "funny quotes about life and happiness", "best motivational quotes", 
    "construction project planning software", "management app", "task software", "free pos", 
    "buy mastercard", "powerful bible verses", "good team quotes for work", "clover pos system", 
    "construction project management tools", "best team management software", "monday.com crm", 
    "best software for project management", "project schedule software", "clover station", 
    "good morning motivational quotes", "positive life quotes", "team management tools", 
    "agile project management software", "honeybook", "quotes about life lessons", 
    "best team management tools", "best software project management", "love quotes for him from the heart", 
    "construction app", "best project management platforms", "top task management software", 
    "teamwork project management app", "home quotes", "team project management software", 
    "construction project software", "quotes about being happy", "simple project tracking software", 
    "most powerful bible verses", "square contactless reader", "happy quotes", "project manager software", 
    "best software for construction management", "project time management software", "purchase visa gift card online", 
    "construction estimating software", "monday.com login", "online visa gift card", "clover cash register", 
    "monday crm demo", "positive quotes for work", "best task management software", "love quotes for boyfriend", 
    "bible quotes about love", "best task management tools", "to do management app", "custom project management software", 
    "love quotes for wife", "love quotes for girlfriend", "project schedule management software", "best quotes", 
    "life changing quotes", "good team management software", "task scheduling software", "project management software for construction", 
    "best construction project management tools", "funny inspirational quotes", "motivation bible verse", "strong bible verses", 
    "pay with paysafecard", "best scheduling software", "square pos", "software for project management", 
    "daily motivational bible verses", "best project software", "funny life quotes", "team task management software", 
    "best visa gift card online", "motivational quotes for life", "short love quotes", "best visa gift card", 
    "construction project management system", "online visa card", "project management software construction", 
    "top management quotes", "team task software", "funny inspirational quotes about life", "motivational quotes about life", 
    "buy online visa gift card", "pmbok guide", "virtual visa", "best love quotes", "pmbok 7th edition", 
    "project and task management software", "best online project management software", "free construction project management software", 
    "positive quotes for life", "funny quotes about love", "project collaboration software", "agile pm tools", 
    "best love quotes for her", "project scheduling management software", "free construction software", 
    "motivational love quotes", "project management tool construction", "construction planning software", 
    "free visa gift card online", "happy life quotes", "buy paysafe", "quote of the day funny", "free project tracking software", 
    "life motivational quotes", "best project software for construction", "best project planning software", 
    "best project management tools construction", "short funny quotes", "task management software for teams", 
    "buy a mastercard gift card", "good leadership quotes", "simple task management software", "project management for construction", 
    "construction task management software", "positive motivational quotes", "free virtual visa card", 
    "powerful quotes about life", "short motivational quotes for work", "free team task management software", 
    "top project management tools construction", "short motivational quotes for success", "team collaboration project management software", 
    "best project scheduling software", "construction management software project", "buy paysafe card", "funny motivational quotes for work", 
    "best quotes for life", "project management tracking software", "best construction project software", 
    "construction tracking software", "funny motivational quotes about work", "construction project management planning software", 
    "short good morning quotes", "construction project software management", "motivational quotes for students", 
    "construction management software tools", "project management software best", "construction project management systems software", 
    "project construction management software", "quotes about life and love", "construction task management app", 
    "good motivational quotes", "construction management project planning software", "construction tracking management software", 
    "best project time tracking software", "good team work quotes", "virtual visa card free", "construction project management software free", 
    "top quotes", "motivational good morning quotes", "best construction tracking software", "team construction project management software", 
    "virtual visa card mastercard", "funny work motivational quotes", "best project management construction software", 
    "construction planning management software", "construction management project scheduling software", "construction project software tools"
    ]
    
};

export default function Page() {
  return (
    <Suspense fallback={<Loading />}>
      <Page_container />
    </Suspense>
  );
}
