import { Suspense } from "react";
import Loading from "./loading";
import dynamic from "next/dynamic";
const Page_container = dynamic(() => import("./Page_sup/Page_container"), { ssr: false })


export const metadata = {
  title: "CLADCUT",
  description:
    "Produce detailed cladding fabrication drawings and CNC files with exceptional speed and efficiency, optimized cutting layouts and clash detection that save time and material, and Precise unfold views and automatic dimensioning minimize errors.",
  keywords: [
    "clad cut", "cladcut", "all clad d3", "all clad d5", "all clad stainless steel", 
    "all clad pans", "all clad waffle maker", "all clad nonstick", "all clad saucepan", 
    "all clad saute pan", "hex clad pans", "all clad ha1", "acp sheet", 
    "all clad immersion blender", "clad pans", "all clad sets", "all clad d5 stainless", 
    "he clad", "all clad d5 stainless steel", "all clad stainless steel pan", 
    "all clad metalcrafters", "all clad grill", "all clad d3 everyday", "acp sheet price", 
    "all clad 4 qt saute pan", "all clad d3 stainless steel", "all clad pressure cooker", 
    "all clad waffle iron", "wall clading", "solid wood panel", "grill all clad", 
    "all clad 6 qt pasta pot", "all clad hand blender", "aluminium composite cladding", 
    "pvc clading", "solid wood paneling for walls", "all clad metalcrafters llc", 
    "viva acp sheet price", "acp sheet 8x4 price", "cladding exterior house", 
    "external wall clading", "pvc wall clading", "brushed aluminum composite panel", 
    "exterior wall clading", "outdoor clading", "aluminium composite panel sheet price", 
    "stone wall clading", "acp wall panels", "wood wall clading", 
    "brushed aluminium composite panel", "4mm aluminum composite panel", 
    "composite panel price", "particle wood board", "exterior house wall cladding", 
    "interior clading", "marble aluminum composite panel", "acp aluminium composite panel price", 
    "acp facade cladding", "acp interior wall cladding", "alco panel price", 
    "aluminium composite material cladding", "aluminum composite panel acp sheet", 
    "aluminum composite panel sheet", "brick wall clading", "cladding aluminum composite panel", 
    "door clading", "eurobond acp sheet", "granite clading", "interior aluminium composite panel", 
    "interior wall clading", "marble clading", "metal wall clading", 
    "perforated aluminium composite panel", "plastic aluminium composite panel price", 
    "slate clading", "solid hardwood panel", "timber wall clading", 
    "viva aluminium panel sheet price", "wood finish acp sheet", "metal manufacturing near me", 
    "sheet metal shop", "woven mesh", "iron mesh", "aluminum cladding panel", 
    "steel cladding sheets", "sheet metal wall panels", "metal sheet wall panels", 
    "aluminium wall cladding panels", "aluminium sandwich panels", 
    "external aluminium cladding", "aluminium cladding price", "aluminium wall panel", 
    "metal wall panelling", "aluminium cladding installations", "aluminum cladding sheet price", 
    "aluminium cladding sheet price", "wall panel aluminum", "acp wall panel", 
    "aluminium profile wall cladding", "aluminium sheet cladding details", 
    "aluminum metal wall panels", "aluminum panel wall", "gi cladding sheet", 
    "gi sheet wall cladding", "ss cladding sheet for insulation", "كلاد كت", "كلادكت", 
    "كلادينج", "كلادنج", "واجهات كلادينج", "تصميم واجهات كلادينج", "تصميم واجهات", 
    "exterior facade design", "3d facade design", "2 storey house facade designs", 
    "external facade design", "facade decor", "facade light design", "facade modern", 
    "home facade designer", "home frontage design", "house facades with stone", 
    "houses with stone facades", "islamic facade design", "minimalist facade design", 
    "modern building facade design", "modern villa facade design", "rhino for revit", 
    "sandstone house facades", "single story facade design", "cladding", "bathroom wall panels", 
    "aluminium windows", "acoustic panels for walls", "pvc cladding", "aluminum patio covers", 
    "aluminium bifold doors", "decorative wall panels", "aluminium doors", 
    "bathroom cladding", "aluminium profile", "wall cladding", "wooden wall panels", 
    "upvc cladding", "cladding panels", "aluminium sliding doors", "aluminium sheet", 
    "aluminum extrusion", "extruded aluminum", "insulated roof panels", "aluminium gates", 
    "aluminum tubing", "aluminum roofing", "plastic wall panels", "stone cladding", 
    "aluminum plate", "slatted wall panels", "aluminium angle", "aluminium", 
    "exterior cladding", "laser metal cutting machine", "aluminum awnings", 
    "aluminium windows near me", "aluminum railing", "house cladding", "fluted wall panels", 
    "wall cladding panels", "stone wall panels", "larch cladding", "wood cladding", 
    "aluminium composite panel", "aluminium doors and windows", "fibre cement cladding", 
    "aluminum diamond plate", "aluminum carport", "composite wall cladding", "aluminum tape", 
    "wpc wall panel", "an fittings", "aluminum channel", "aluminum roof", "aluminum pipe", 
    "aluminium patio doors", "external wall cladding", "white cladding", "roof panels", 
    "pvc bathroom wall panels", "ceiling cladding", "concrete wall panels", "metal cladding", 
    "stone veneer exterior", "aluminium scaffold tower", "waterproof bathroom wall panels", 
    "waterproof wall panels", "aluminium venetian blinds", "aluminum stairs", 
    "exterior wall cladding", "aluminium online", "aluminium canopy", 
    "wood cladding exterior", "pvc wall cladding", "aluminium shutters", 
    "aluminum extrusion profiles", "aluminum siding panels", "aluminium box section", 
    "slatted wood wall panels", "wood veneer wall panels", "aluminum flat bar", 
    "shed cladding", "wall covering panels", "aluminum roof panels", "aluminium scaffolding", 
    "aluminium ladder", "marble wall panels", "aluminium bi fold doors", "aluminium blinds", 
    "perforated aluminum sheet", "exterior wall panels", "oak wall panels", "stone wall cladding", 
    "decorative wood panels for walls", "aluminum pool fence", "aluminum u channel", 
    "aluminum screen doors", "stainless steel wall panels", "metal wall panels", 
    "t slot aluminum", "aluminium fence panels", "bamboo wall panels", 
    "aluminum welding rods", "aluminum c channel", "outdoor cladding", 
    "aluminium sliding patio doors", "grey cladding", "natural stone veneer", 
    "outdoor wall panels", "aluminum bar", "interior wall cladding", "thin stone veneer", 
    "aluminum railing systems", "stone cladding exterior", "pvc panels for walls", "7075 aluminum", 
    "aluminium windows prices", "roof cladding", "thermowood cladding", "aluminum paint", 
    "aluminum foil tape", "aluminium window frames", "aluminium box", "aluminum brazing rod", 
    "aluminium strip", "6061 aluminum", "aluminum fence gate", "black aluminium windows", 
    "aluminium angle trim", "wpc panel", "aluminium plantation shutters", "black wall panels", 
    "aluminum gutter guards", "aluminum rod", "metal tile trim", "aluminum grating", 
    "aluminum welding machine", "aluminum coil", "acoustic wall panels decorative", 
    "metal window awnings", "aluminum wire", "aluminum sliding glass doors", 
    "interior wall paneling", "aluminium roofing sheet", "exterior wall cladding panels", 
    "wall panels living room", "tongue and groove wall panels", "aluminum landscape edging", 
    "wood cladding interior", "black cladding", "outdoor wall cladding", "alucobond cladding", 
    "aluminium scaffolding for sale", "exterior cladding panels", "aluminum panels", 
    "aluminum honeycomb panels", "sandstone cladding", "metal stair nosing", 
    "aluminium stair nosing", "aluminum stair nosing", "white pvc cladding", 
    "extruded aluminum t slot", "timber wall panels", "aluminum edging", "rock wall panels", 
    "aluminum corner guards", "aluminium led profile", "metal cladding panels", 
    "aluminium windows and doors near me", "acoustic wall", "aluminum extension ladder", 
    "pvc ceiling cladding", "aluminium chequer plate", "aluminum step ladder", 
    "aluminum tread plate", "corrugated aluminium roofing sheets", "marine aluminum", 
    "extruded aluminum channel", "aluminum u channel sizes", "aluminum bar stock", 
    "wood wall covering panels", "aluminum vents", "metal stair nosing anti slip", 
    "corrugated aluminium sheet", "window cladding", "aluminum siding sheets", 
    "composite aluminum panel", "wooden decorative wall panels", "brushed aluminum", 
    "aluminium sliding door track", "wainscoting wall panels", "small aluminum ladder", 
    "grey wall panels", "wood wall panels living room", "stainless steel corner guards", 
    "metal corner guards", "stainless corner guards", "timber cladding", 
    "timber cladding exterior", "external stone cladding", "black aluminium doors", 
    "grey aluminium windows", "modern house cladding", "modern cladding", "concrete cladding", 
    "rustic wood cladding", "wood cladding wall panels", "glass cladding", 
    "decorative cladding panels", "bamboo cladding", "internal wall cladding", 
    "perforated metal cladding", "modern wall cladding", "aluminum fence slats", 
    "concrete wall cladding", "brick cladding", "aluminium corner profile", 
    "aluminium channel sizes", "larch cladding prices", "aluminum window manufacturers near me", 
    "cedar cladding"
],
};
export default function Page() {
  return (
    <Suspense fallback={<Loading />}>
      <Page_container />
    </Suspense>
  );
}
