"use client"
import Footer from '@/components/Layout/Footer/Footer'
import Header from '@/components/Layout/Header/Header'
import Page_sup from './Page_contant'
import Loading_page from '@/components/Loading_page/Loading_page'
import { useEffect, useState } from 'react'
import ScrollToTop from "react-scroll-to-top";
import Contact from '@/components/Contact/Contact'


export const metadata = {
    title: "CLADCUT",
    description: "Generated by create next app",
  };
  

export default function Page() {
    const [showTimer , setShowTimer] = useState(0)
    const [toggle, setToggle] = useState(false);

    const handleToggle = () => {
      setToggle(!toggle);
  }
    function handleTimer(){
      setShowTimer(showTimer + 1)
    }
  
    useEffect(()=>{
      if(showTimer < 2){
      setTimeout(handleTimer,1000)
      console.log('timer')
      }
    },[showTimer])

  return (
    
    <div className='page_hid'>

        <Header handleToggle={handleToggle}/>
          <Page_sup />
        <Footer />
      <ScrollToTop smooth color="#fff" style={{backgroundColor:'#525A63', padding:'5px', borderRadius: '50%',left:'20px'}} />
      <Contact handleToggle={handleToggle} toggle={toggle} setToggle={setToggle}/>
    </div>
  )
}
