import React from 'react'
import { Col, Container, Row } from 'reactstrap'
import Privacy from "@/assets/images/Products_Page/privacy/privacy.jpg"


export default function Section_1() {
  return (
    <section className='privacy-content'>
        <Container>
            <div>
            <div className="article-content mb-5">
                  <h2>Terms and Conditions</h2>
                  <h3>Privacy Policy</h3>
                  <p>Last Updated: July 14, 2024</p>
                  <p>
                    This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.
                  </p>
                  <p>
                    We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
                  </p>

                  <h2>Interpretation and Definitions</h2>
                  <h3>Definitions</h3>
                  <p>For the purposes of this Privacy Policy:</p>
                  <ul>
                    <li>
                      <strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.
                    </li>
                    <li>
                      <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.
                    </li>
                    <li>
                      <strong>Application</strong> refers to DomApp, the software program provided by the Company.
                    </li>
                    <li>
                      <strong>Company</strong> (referred to as either "the Company," "We," "Us," or "Our" in this Agreement) refers to DomApp.
                    </li>
                    <li>
                      <strong>Cookies</strong> are small files that are placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among its many uses.
                    </li>
                    <li>
                      <strong>Country</strong> refers to Egypt.
                    </li>
                    <li>
                      <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.
                    </li>
                    <li>
                      <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
                    </li>
                    <li>
                      <strong>Service</strong> refers to the Application or the Website or both.
                    </li>
                    <li>
                      <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.
                    </li>
                    <li>
                      <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </li>
                    <li>
                      <strong>Website</strong> refers to DomApp, accessible from www.domapphub.com.
                    </li>
                    <li>
                      <strong>You</strong> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                    </li>
                  </ul>

                  <h2>Collection and Use of Your Personal Data</h2>
                  <h3>Types of Data Collected</h3>
                  <ul>
                    <li>
                      <strong>Personal Data</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
                      <ul>
                        <li>National ID / Residence ID</li>
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Mobile number</li>
                      </ul>
                    </li>
                    <li>
                      <strong>Usage Data</strong> Usage data is collected automatically when using the service.
                      <p>Usage data may include information such as your device's Internet Protocol address (like IP address), browser type, browser version, the pages of the service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>
                      <p>When accessing the service by or through a mobile device, we may collect certain information automatically, including, but not limited to:</p>
                      <ul>
                        <li>The type of mobile device you use</li>
                        <li>Your mobile device unique ID</li>
                        <li>The IP address of your mobile device</li>
                        <li>Your mobile operating system</li>
                        <li>The type of mobile internet browser you use</li>
                        <li>Unique device identifiers</li>
                        <li>Other diagnostic data</li>
                      </ul>
                      <p>We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device.</p>
                    </li>
                    <li>
                      <strong>Information Collected While Using the Application</strong>
                      <p>While using our application, in order to provide features of our application, we may collect, with your prior permission:</p>
                      <ul>
                        <li>Information About Your Site</li>
                        <li>Information from Your Device's Phone Book (Contact List)</li>
                        <li>Photos and Other Information from Your Device's Camera and Photo Library</li>
                      </ul>
                      <p>We use this information to provide features of our service, to improve and customize our service. The information may be uploaded to the company’s servers and/or a service provider’s server, or it may simply be stored on your device.</p>
                      <p>You can enable or disable access to this information at any time, through your device settings.</p>
                    </li>
                  </ul>

                  <h2>Tracking Technologies and Cookies</h2>
                  <p>
                    We use cookies and similar tracking technologies to track the activity on our service and store certain information. The tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our service. The technologies we use may include:
                  </p>
                  <ul>
                    <li>
                      <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our service. Unless you have adjusted your browser settings so that it will refuse cookies, our service may use cookies.
                    </li>
                    <li>
                      <strong>Web Beacons:</strong> Certain sections of our service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                    </li>
                    <li>
                      Cookies can be "persistent" or "session" cookies. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser. Learn more about cookies on the Privacy Policies website article.
                    </li>
                  </ul>

                  <h3>Types of Cookies We Use</h3>
                  <ul>
                    <li>
                      <strong>Necessary / Essential Cookies:</strong>
                      <ul>
                        <li>Type: Session Cookies</li>
                        <li>Administered by: Us</li>
                        <li>Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services that you have asked for cannot be provided, and we only use these cookies to provide you with those services.</li>
                      </ul>
                    </li>
                    <li>
                      <strong>Cookies Policy / Notice Acceptance Cookies:</strong>
                      <ul>
                        <li>Type: Persistent Cookies</li>
                        <li>Administered by: Us</li>
                        <li>Purpose: These cookies identify if users have accepted the use of cookies on the website.</li>
                      </ul>
                    </li>
                    <li>
                      <strong>Functionality Cookies:</strong>
                      <ul>
                        <li>Type: Persistent Cookies</li>
                        <li>Administered by: Us</li>
                        <li>Purpose: These cookies allow us to remember choices you make when you use the website, such as remembering your login details or language preferences. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the website.</li>
                      </ul>
                    </li>
                  </ul>

                  <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

                  <h2>Use of Your Personal Data</h2>
                  <p>The company may use personal data for the following purposes:</p>
                  <ul>
                    <li>To provide and maintain our service, including monitoring the usage of our service.</li>
                    <li>To manage your account: to manage your registration as a user of the service. The personal data you provide can give you access to different functionalities of the service that are available to you as a registered user.</li>
                    <li>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or any other contract with us through the service.</li>
                  </ul>
    <p>to contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as mobile application push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
    
    <h2>To provide you with:</h2>
    <ul>
        <li>News, special offers, and general information about goods, services, and other events we offer that are similar to those you have already purchased or inquired about, unless you have opted not to receive such information.</li>
    </ul>
    
    <h2>To manage your requests:</h2>
    <ul>
        <li>To attend to and manage your requests to us.</li>
    </ul>
    
    <h2>For other purposes:</h2>
    <ul>
        <li>We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our services, products, marketing, and your experience.</li>
    </ul>
    
    <h2>We may share your personal information in the following situations:</h2>
    <ul>
        <li>With Service Providers: We may share your personal information with service providers to monitor and analyze the use of our service, to contact you.</li>
        <li>For Business Transfers: We may share or transfer your personal information in connection with or during negotiations of any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</li>
        <li>With Business Partners: We may share your information with our business partners to offer you certain products, services, or promotions.</li>
        <li>With Other Users: When you share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
        <li>With Your Consent: We may disclose your personal information for any other purpose with your consent.</li>
    </ul>
    
    <h2>Retention of Your Personal Data</h2>
    <p>The company will retain your personal data only as long as necessary for the purposes set out in this Privacy Policy. We will retain and use your data as necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
    
    <p>The company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
    
    <p>After that, the data will be destroyed in a secure manner that cannot be viewed or retrieved again as issued by regulatory authorities.</p>
    
    <h2>Transfer of Your Personal Data</h2>
    <p>Your information, including personal data, is processed at the company's operating offices and in any other places where the parties involved in the processing are located, meaning this information may be transferred to — and maintained on — computers located outside of Egypt after obtaining written consent from the regulatory authority. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
    
    <p>The company will take all the steps reasonably necessary to ensure that your data is treated securely.</p>
    
    <h2>Delete Your Personal Data</h2>
    <p>You have the right to delete the personal data we have collected about you, update your information, or modify it at any time by logging into your account, visiting the account settings section that allows you to manage your personal information, or by contacting us to request access to, correct, or delete any personal information you have provided to us unless there is a statutory text specifying a certain period for retention or contractual requirements.</p>
    
    <p>You also have the right to withdraw consent to the processing of your personal data at any time unless there are legitimate grounds that require otherwise.</p>
    
    <h2>Disclosure of Your Personal Data</h2>
    <p><strong>Law Enforcement</strong><br />
    Under certain circumstances, the company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
    
    <p><strong>Other Legal Requirements</strong><br />
    The company may disclose your personal data in the good faith belief that such action is necessary to:</p>
    <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of users of the Service or the public</li>
        <li>Protect against legal liability</li>
    </ul>
    
    <h2>Security of Your Personal Data</h2>
    <p>Personal data is stored within Egypt on servers that are protected by the best technologies in compliance with the policies and controls of the National Cybersecurity Authority to ensure unauthorized access is prevented and to minimize cybersecurity risks.</p>
    
    <h2>Children's Privacy</h2>
    <p>You must be at least 18 years old to use our Services. By using our Services, you represent and warrant that you meet this age requirement, Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 18 without verification of parental consent, we take steps to remove such information from our servers.</p>
    
    <p>If we need to rely on consent as a legal basis for processing your information and your country requires parental consent, we may seek your parent's consent before collecting and using this information.</p>
    
    <h2>Links to Other Websites</h2>
    <p>Our service may contain links to other websites that we do not operate. If you click on a third-party link, you will be directed to that third party's site.</p>
    
    <p>We strongly advise you to review the privacy policy of every site you visit.</p>
    
    <p>We have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
    
    <h1>Cancellation and Refund Policy</h1>
    
    <h2>1. Introduction</h2>
    <p>This Cancellation and Refund Policy ("Policy") applies to all services provided by DomApp, including application and software development or customizations, and any related services offered by our business departments. By engaging our services, you agree to be bound by this Policy.</p>
    
    <h2>2. Project Cancellation</h2>
    
    <h3>2.1. Client-Initiated Cancellation</h3>
    <p><strong>Notification:</strong> Clients may cancel their projects at any time by providing written notice to DomApp via email or other agreed-upon communication methods.</p>
    <p><strong>Refund Eligibility:</strong> Eligibility for a refund will be determined based on the stage of the project and the work completed up to the point of cancellation.</p>
    
    <h3>2.2. Company-Initiated Cancellation</h3>
    <p>DomApp reserves the right to cancel any project at its discretion if the client violates the terms of the agreement or engages in any behavior that makes the continuation of the project unfeasible. In such cases, DomApp will provide written notice to the client.</p>
    
    <h2>3. Refund Policy</h2>
    
    <h3>3.1. Refund Eligibility</h3>
    <p><strong>Initial Consultation and Planning:</strong> Fees for initial consultation and project planning are non-refundable.</p>
    <p><strong>Project Milestones:</strong> Refunds for work completed on specific milestones will be assessed based on the progress and deliverables provided. Clients will be refunded for uncompleted milestones, less any costs incurred by DomApp up to that point.</p>
    
    <h3>3.2. Non-Refundable Services</h3>
    <p>Certain services and fees are non-refundable, including but not limited to:</p>
    <ul>
        <li>Bundles, Quota, packages, services, etc. already initiated.</li>
        <li>Services provided by third-party vendors or contractors.</li>
        <li>Any work completed and delivered to the client prior to the cancellation request.</li>
    </ul>
    
    <h3>3.3. Refund Process</h3>
    <p><strong>Requesting a Refund:</strong> Clients must submit a refund request in writing, detailing the reason for the cancellation.</p>
    <p><strong>Review and Approval:</strong> DomApp will review the refund request and determine eligibility based on the criteria outlined in this Policy. The client will be notified of the decision within 14 business days.</p>
    <p><strong>Refund Issuance:</strong> Approved refunds will be processed within 10 to 45 days, using the original payment method.</p>
    
    <h2>4. Dispute Resolution</h2>
    <p>In the event of a dispute regarding a cancellation or refund, clients are encouraged to contact DomApp's customer service team to resolve the issue. If a resolution cannot be reached, the dispute may be escalated to arbitration, or legal proceedings as outlined in the Terms and Conditions.</p>
    
    <h2>5. Changes to This Privacy Policy</h2>
    <p>DomApp reserves the right to modify or update this at any time. Clients will be notified of any significant changes via email or through this page.</p>
    
    <p>We advise you to review this privacy policy periodically for any changes. Changes to this privacy policy are effective when they are posted on this page.</p>
    
    <p>Continued use of our services after any changes indicates acceptance of the new Policy.</p>
    
    {/* <p>The Arabic language is the official language for applying terms and conditions, and in case of any dispute in interpreting any text written in another language, the Arabic text will be considered.</p> */}
    

    <h2>Contact Us</h2>
    <p>If you have any questions or complaints regarding the privacy policy, you can contact us via email: 
      <a href="mailto:contactus@domapphub.com">contactus@domapphub.com</a></p>
                </div>
            </div>
            <div>
                    <Row>
                        <Col sm={12} lg={4} md={6}>
                            <img src={Privacy.src} alt="privacy" />
                        </Col>
                    </Row>
                </div>
        </Container>
    </section>
  )
}
