import Head from 'next/head';
import { Inter } from "next/font/google";
import "./globals.css";
import "../style/main.css"
import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import { AOSInit } from "@/components/Animation/aos";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DomApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AOSInit />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
