// import Head from "next/head";
import "./globals.css";
import "../style/main.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import StoreProvider from "@/store/Provider/StoreProvider";
import Script from "next/script";
import { AOSInit } from "@/components/Animation/aos";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";

export const metadata = {
  title: "DomApp",
  description: "Generated by create next app",
  metadataBase: new URL("https://domapp.com"),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="public/images/favicon.ico" type="image/x-icon" />
        {/* <link rel="shortcut icon" href="/images/favicon.ico" /> */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </>
      <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=G-0P9TXL8XCE"
      />

      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-0P9TXL8XCE');
        `}
      </Script>
      {/* Google Tag Manager */}
      <Script
        id="google-tag-manager"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-WHTW6XJK');
          `,
        }}
      />

      {/* Microsoft Clarity */}
      <Script
        id="microsoft-clarity"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "pae61uy1le");
          `,
        }}
      />
      {/* Yandex.Metrika */}
      <Script
        id="yandex-metrika"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
          m[i].l=1*new Date();
          for (var j = 0; j < document.scripts.length; j++) {
              if (document.scripts[j].src === r) { return; }
          }
          k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
          (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

          ym(99154524, "init", {
              clickmap:true,
              trackLinks:true,
              accurateTrackBounce:true,
              webvisor:true
          });
          `,
        }}
      />
      <body
        suppressHydrationWarning={true}
        style={{ fontFamily: "Alexandria" }}
      >
        <StoreProvider>
          <ClientWrapper>{children}</ClientWrapper>
          <AOSInit />
        </StoreProvider>
        {/* <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-WHTW6XJK"
            height="0"
            width="0"
            style="display:none;visibility:hidden"
          ></iframe>
        </noscript>
        <noscript>
          <div>
            <img loading="lazy" 
              src="https://mc.yandex.ru/watch/99154524"
              style="position:absolute; left:-9999px;"
              alt=""
            />
          </div>
        </noscript> */}
      </body>
    </html>
  );
}
