import { Suspense } from "react";
import Loading from "./loading";
import dynamic from "next/dynamic";
const Page_container = dynamic(() => import("./Page_sup/Page_container"), {
  ssr: false,
});
export const metadata = {
  title: "GRASSHOPPER",
  description:
    "Grasshopper Modules is a service that utilizes Grasshopper as a powerful tool for our experienced facade designers to generate and design solutions that meet client needs for their structures. Our team leverages the capabilities of parametric design to create complex facade geometries and optimize performance, ensuring both aesthetic appeal and functionality. By employing real-time visualization, material analysis, and structural optimization, we deliver customized designs that align with the specific requirements of each project, empowering clients to achieve their architectural vision.",
  keywords:[
    "exterior facade design",
    "3d facade design",
    "2 storey house facade designs",
    "external facade design",
    "facade decor",
    "facade light design",
    "facade modern",
    "home facade designer",
    "home frontage design",
    "house facades with stone",
    "houses with stone facades",
    "islamic facade design",
    "minimalist facade design",
    "modern building facade design",
    "modern villa facade design",
    "rhino for revit",
    "sandstone house facades",
    "single story facade design",
    "cladding",
    "bathroom wall panels",
    "aluminium windows",
    "acoustic panels for walls",
    "pvc cladding",
    "aluminum patio covers",
    "aluminium bifold doors",
    "decorative wall panels",
    "aluminium doors",
    "bathroom cladding",
    "aluminium profile",
    "wall cladding",
    "wooden wall panels",
    "upvc cladding",
    "cladding panels",
    "aluminium sliding doors",
    "aluminium sheet",
    "aluminum extrusion",
    "extruded aluminum",
    "insulated roof panels",
    "aluminium gates",
    "aluminum tubing",
    "aluminum roofing",
    "plastic wall panels",
    "stone cladding",
    "aluminum plate",
    "slatted wall panels",
    "aluminium angle",
    "aluminium",
    "exterior cladding",
    "laser metal cutting machine",
    "aluminum awnings",
    "aluminium windows near me",
    "aluminum railing",
    "house cladding",
    "fluted wall panels",
    "wall cladding panels",
    "stone wall panels",
    "larch cladding",
    "wood cladding",
    "aluminium composite panel",
    "aluminium doors and windows",
    "fibre cement cladding",
    "aluminum diamond plate",
    "aluminum carport",
    "composite wall cladding",
    "aluminum tape",
    "wpc wall panel",
    "an fittings",
    "aluminum channel",
    "aluminum roof",
    "aluminum pipe",
    "aluminium patio doors",
    "external wall cladding",
    "white cladding",
    "roof panels",
    "pvc bathroom wall panels",
    "ceiling cladding",
    "concrete wall panels",
    "metal cladding",
    "stone veneer exterior",
    "aluminium scaffold tower",
    "waterproof bathroom wall panels",
    "waterproof wall panels",
    "aluminium venetian blinds",
    "aluminum stairs",
    "exterior wall cladding",
    "aluminium online",
    "aluminium canopy",
    "wood cladding exterior",
    "pvc wall cladding",
    "aluminium shutters",
    "aluminum extrusion profiles",
    "aluminum siding panels",
    "aluminium box section",
    "slatted wood wall panels",
    "wood veneer wall panels",
    "aluminum flat bar",
    "shed cladding",
    "wall covering panels",
    "aluminum roof panels",
    "aluminium scaffolding",
    "aluminium ladder",
    "marble wall panels",
    "aluminium bi fold doors",
    "aluminium blinds",
    "perforated aluminum sheet",
    "exterior wall panels",
    "oak wall panels",
    "stone wall cladding",
    "decorative wood panels for walls",
    "aluminum pool fence",
    "aluminum u channel",
    "aluminum screen doors",
    "stainless steel wall panels",
    "metal wall panels",
    "t slot aluminum",
    "aluminium fence panels",
    "bamboo wall panels",
    "aluminum welding rods",
    "aluminum c channel",
    "outdoor cladding",
    "aluminium sliding patio doors",
    "grey cladding",
    "natural stone veneer",
    "outdoor wall panels",
    "aluminum bar",
    "interior wall cladding",
    "thin stone veneer",
    "aluminum railing systems",
    "stone cladding exterior",
    "pvc panels for walls",
    "7075 aluminum",
    "aluminium windows prices",
    "roof cladding",
    "thermowood cladding",
    "aluminum paint",
    "aluminum foil tape",
    "aluminium window frames",
    "aluminium box",
    "aluminum brazing rod",
    "aluminium strip",
    "6061 aluminum",
    "aluminum fence gate",
    "black aluminium windows",
    "aluminium angle trim",
    "wpc panel",
    "aluminium plantation shutters",
    "black wall panels",
    "aluminum gutter guards",
    "aluminum rod",
    "metal tile trim",
    "aluminum grating",
    "aluminum welding machine",
    "aluminum coil",
    "acoustic wall panels decorative",
    "metal window awnings",
    "aluminum wire",
    "aluminum sliding glass doors",
    "interior wall paneling",
    "aluminium roofing sheet",
    "exterior wall cladding panels",
    "wall panels living room",
    "tongue and groove wall panels",
    "aluminum landscape edging",
    "wood cladding interior",
    "black cladding",
    "outdoor wall cladding",
    "alucobond cladding",
    "aluminium scaffolding for sale",
    "exterior cladding panels",
    "aluminum panels",
    "aluminum honeycomb panels",
    "sandstone cladding",
    "metal stair nosing",
    "aluminium stair nosing",
    "aluminum stair nosing",
    "white pvc cladding",
    "extruded aluminum t slot",
    "timber wall panels",
    "aluminum edging",
    "rock wall panels",
    "aluminum corner guards",
    "aluminium led profile",
    "metal cladding panels",
    "aluminium windows and doors near me",
    "acoustic wall",
    "aluminum extension ladder",
    "pvc ceiling cladding",
    "aluminium chequer plate",
    "aluminum step ladder",
    "aluminum tread plate",
    "interior stone veneer",
    "aluminum screen",
    "white aluminum",
    "upvc wall panels",
    "aluminum rectangular tubing",
    "cheap wall paneling",
    "wire nut",
    "3d wood wall panels",
    "interior cladding",
    "aluminum steps",
    "aluminium sheet price",
    "aluminium windows online",
    "aluminum porch railing",
    "feature wall panels",
    "ceiling cladding panels",
    "external aluminium doors",
    "slate cladding",
    "aluminum roof panels prices",
    "aluminum platform",
    "aluminum expanded metal",
    "wpc cladding",
    "aluminum louvers",
    "pvc marble wall panels",
    "aluminium sliding doors prices",
    "veneer wall panels",
    "aluminum scaffolding for sale",
    "aluminum sheet metal near me",
    "wood wall cladding",
    "insulated aluminum roof panels",
    "wpc wall cladding",
    "aluminium cladding panels",
    "aluminium sliding window",
    "aluminum frame",
    "aluminium glass door",
    "metal wall cladding",
    "soundproofing wall panels",
    "upvc ceiling cladding",
    "aluminum attic ladder",
    "aluminum trim",
    "aluminum post",
    "aluminum round stock",
    "aluminum mesh",
    "aluminium coil",
    "aluminum hinges",
    "aluminum tube stock",
    "stone veneer cladding",
    "3d panel wall",
    "upvc cladding exterior",
    "t slot aluminium extrusion",
    "3mm aluminium sheet",
    "aluminium door frame",
    "aluminum truss",
    "waterproof bathroom panels",
    "grey wall panels",
    "exterior paneling",
    "double glazed aluminium windows",
    "timber wall cladding",
    "upvc wall cladding",
    "plastic bathroom wall panels",
    "aluminum wall panels",
    "aluminum duct tape",
    "aluminum honeycomb",
    "burnt wood cladding",
    "aluminium entrance doors",
    "aluminium casement windows",
    "flexible wall panels",
    "aluminum extrusions near me",
    "tile wall panels",
    "aluminum welding wire",
    "steel wall panels",
    "7075 t6",
    "cement wall panels",
    "plastic bathroom panels",
    "aluminum screen frame",
    "aluminium doors prices",
    "aluminum straight edge",
    "4040 aluminum extrusion",
    "aluminium roller shutter",
    "brick slip cladding",
    "aluminum screws",
    "alucobond sheet",
    "aluminium folding doors",
    "residential insulated roof panels",
    "extruded aluminum profiles",
    "insulation panels for walls",
    "aluminum angle bar",
    "aluminum conduit",
    "brick cladding panels",
    "aluminium round bar",
    "plastic ceiling cladding",
    "aluminum scoop shovel",
    "corten steel cladding",
    "expanded aluminum",
    "plywood wall panels",
    "aluminum ceiling tiles",
    "aluminum beams",
    "aluminum cable tray",
    "2mm aluminium sheet",
    "exterior house cladding",
    "aluminium skirting",
    "aluminum l channel",
    "aluminum composite material",
    "aluminum track channel",
    "ribbed wall panels",
    "aluminum screen wire",
    "aluminum sliding windows",
    "aluminum garage doors",
    "aluminum double doors",
    "insulated cladding",
    "polished aluminum sheet",
    "aluminium fencing panels",
    "3d wall cladding panels",
    "aluminium venetian blinds made to measure",
    "aluminum composite panel cladding",
    "metal wall cladding panels",
    "diy wall panels",
    "aluminum flashings",
    "aluminium extrusion profiles",
    "aluminium window section",
    "bathroom wall boards",
    "wall cladding interior",
    "exterior wall panels cladding",
    "bronze aluminum",
    "bathroom splashback panels",
    "anodized aluminum sheet",
    "pvc wall covering",
    "aluminum industrial ladder",
    "aluminium bar stock",
    "white wood wall panels",
    "thermally broken aluminium windows",
    "aluminum extrusion table",
    "aluminium section",
    "pvc panel",
    "aluminium shop front",
    "black aluminum",
    "aluminum floor jack",
    "bronze aluminium windows",
    "decorative acoustic wall panels",
    "aluminium box section sizes",
    "folding aluminium doors",
    "pvc tongue and groove cladding",
    "silver aluminium windows",
    "aluminum electrical wire",
    "3d pvc wall panels",
    "marble cladding",
    "black aluminium door",
    "aluminum rod stock",
    "extruded aluminium sections",
    "wood panelling for walls",
    "lightweight aluminum ladder",
    "3mm aluminum sheet",
    "aluminum trim coil",
    "external wall cladding system",
    "aluminium window grills",
    "corten wall panels",
    "acp cladding",
    "aluminum post caps",
    "oak wall panelling",
    "decorative cladding",
    "insulated aluminium roof panels",
    "aluminum plate sheet",
    "brushed aluminium sheet",
    "bathroom panel boards",
    "residential exterior cladding",
    "wood effect wall panels",
    "interior feature wall panels",
    "fiber cement exterior panels",
    "aluminum construction ladder",
    "custom aluminium extrusions",
    "black aluminum window frames",
    "wood and metal wall panels",
    "decorative wall boards",
    "pvc stone cladding",
    "aluminium windows manufacturers",
    "metal cladding wall panels",
    "panel system",
    "grey feature wall panels",
    "oak panelling",
    "external cladding systems",
    "metal cladding sheets",
    "black wall cladding",
    "waterproof pvc wall panels",
    "exterior architectural wall panels",
    "wood plastic wall panel",
    "external wall cladding material",
    "pvc cladding system",
    "laser cut aluminium panels",
    "metal shed cladding",
    "aluminium shed",
    "thermally broken aluminium doors",
    "brick wall cladding panels",
    "metal wall coverings",
    "wainscoting wall panels",
    "modern feature wall panels",
    "fireproof cladding",
    "stone cladding near me",
    "pvc wall",
    "extruded aluminium channel",
    "aluminum profile near me",
    "aluminum sliding door",
    "pvc wood panels",
    "aluminum mesh sheet",
    "corten steel exterior wall cladding",
    "aluminium door section",
    "external timber cladding",
    "recycled aluminium",
    "natural stone cladding exterior",
    "galvanised wall panels",
    "aluminium entrance door",
    "outdoor stone cladding",
    "aluminium structural glazing",
    "white aluminum coil",
    "kitchen cladding",
    "wall sheets",
    "bathroom panel board",
    "interior stone cladding",
    "black metal cladding",
    "metal wall trim",
    "modern aluminium windows",
    "aluminum wall trim",
    "aluminium corner profile",
    "silver aluminium windows",
    "lightweight aluminium ladder",
    "white wall panels",
    "residential exterior wall panels",
    "aluminium extrusion",
    "kitchen cladding",
    "black sheet metal cladding"
  ]
    
};

export default function Page() {
  return (
    <Suspense fallback={<Loading />}>
      <Page_container />
    </Suspense>
  );
}
