import Page_container from "./Page_sup/Page_container"
export const metadata = {
    title: "WINDMASTER",
    description: "Generated by create next app",
  };
  

export default function Page() {


  return (
    
    <>
        <Page_container />
    </>
  )
}
