import Page_container from "./Page_sup/Page_container";
export const metadata = {
  title: "CUSTOMIZATION",
  description: "Custom Software Service provides tailored software solutions and customization for any software to address the unique needs of businesses across diverse industries. Our team collaborates closely with clients to grasp their requirements, ensuring the software we develop aligns with their objectives. We oversee the entire software lifecycle, from initial consultation and design to development and ongoing support, delivering scalable and user-friendly applications that boost productivity and foster innovation. Whether you require a web application, or enterprise software, our custom solutions empower your business to thrive.",
  keywords:[
    "logo design", 
    "project management software", 
    "adobe creative cloud", 
    "adobe illustrator", 
    "autocad", 
    "accounting software for small business", 
    "interior design", 
    "free project management software", 
    "best project management software", 
    "t shirt design", 
    "house plans", 
    "free accounting software", 
    "business card design", 
    "free crm software", 
    "bathroom design", 
    "interior design software", 
    "autocad software", 
    "living room ideas", 
    "help desk software", 
    "free accounting software for small business", 
    "video editing app", 
    "logo design online", 
    "adobe cc", 
    "interior design programs", 
    "small bathroom ideas", 
    "construction project management software", 
    "room designer", 
    "home design software", 
    "wall art decor", 
    "bathroom design ideas", 
    "bedroom design", 
    "graphic design software", 
    "graphic design programs", 
    "small kitchen ideas", 
    "house design", 
    "home office ideas", 
    "custom logo maker", 
    "bathroom tile ideas", 
    "home interior design", 
    "bathroom decor ideas", 
    "property management app", 
    "personal accounting software", 
    "home design 3d", 
    "living room decor ideas", 
    "bedroom decor ideas", 
    "customer support software", 
    "hr system software", 
    "office design", 
    "adobe creative", 
    "service desk software", 
    "bathroom wall decor", 
    "clothing design software", 
    "kitchen design software", 
    "recording software", 
    "microsoft project management software", 
    "sticker design", 
    "production scheduling software", 
    "wall decor for living room", 
    "create company logo", 
    "small house plans", 
    "modern bathroom ideas", 
    "video recording software", 
    "adobe products", 
    "accounting app", 
    "living room decor", 
    "free invoice maker app", 
    "free ats", 
    "invoice system", 
    "wassily chair", 
    "production planning software", 
    "kitchen interior design", 
    "resource management software", 
    "top project management software", 
    "adobe illustrator cost", 
    "pdf editor software", 
    "app building software", 
    "fireplace ideas", 
    "invoice maker app", 
    "small kitchen design", 
    "company logo generator", 
    "adobe video editing software", 
    "bed design", 
    "shower tile ideas", 
    "modern living room ideas", 
    "bedroom design ideas", 
    "coreldraw graphics suite", 
    "small living room ideas", 
    "design home", 
    "decoration", 
    "master bedroom ideas", 
    "erp accounting software", 
    "free crm app", 
    "home accounting software", 
    "free timesheet app", 
    "home decor ideas", 
    "asset tracking system", 
    "3d house design", 
    "kitchen decor ideas", 
    "living room design", 
    "staircase design", 
    "app making software", 
    "business logo design free", 
    "free business logo maker", 
    "best warehouse management system", 
    "interior design software free", 
    "construction management app", 
    "small bathroom designs", 
    "professional logo maker", 
    "adobe illustrator price", 
    "free inventory app", 
    "interior design ideas", 
    "loan origination software", 
    "adobe apps", 
    "business software programs", 
    "visiting card design", 
    "top 10 crm software", 
    "staircase ideas", 
    "brand logo maker", 
    "room decor ideas", 
    "best help desk software", 
    "bathroom tiles design", 
    "master bathroom ideas", 
    "free blueprint maker", 
    "best time tracking app", 
    "media wall ideas", 
    "best interior design software", 
    "living room design ideas", 
    "free live chat app", 
    "japandi", 
    "interior design styles", 
    "adobe suite subscription", 
    "open source project management software", 
    "dining room ideas", 
    "coreldraw 2022", 
    "microsoft office package", 
    "menu creator free", 
    "house interior design", 
    "floor plan designer free", 
    "music editing software", 
    "3d home design software", 
    "adobe illustrator classes", 
    "microsoft 365 key", 
    "modern house design", 
    "living room wall decor ideas", 
    "small kitchen design ideas", 
    "best home design software", 
    "create free landing page", 
    "3d interior design software", 
    "open source accounting software", 
    "3d logo maker", 
    "free billing software for pc", 
    "room decoration", 
    "ai graphic design generator", 
    "mobile app development software", 
    "bedroom interior design", 
    "revit 2022", 
    "box design", 
    "furniture design", 
    "free accounting app", 
    "ceiling design", 
    "free accounting software download", 
    "best web design software", 
    "home design ideas", 
    "video editing software for pc", 
    "logo design generator", 
    "bespoke software development", 
    "best database software", 
    "budget software free", 
    "free app development software", 
    "wall design", 
    "living room interior design", 
    "accounting system software", 
    "ae editing app", 
    "cloud based crm", 
    "android app development software", 
    "free video editor software", 
    "tv wall design", 
    "agile project management software", 
    "japandi style", 
    "label maker online", 
    "3d floor planner", 
    "wardrobe design for bedroom", 
    "false ceiling design", 
    "microsoft office products", 
    "house design ideas", 
    "crm software list", 
    "custom logo creator", 
    "tote bag design", 
    "best app development software", 
    "coreldraw 2023", 
    "cupboard design", 
    "building design app", 
    "3d architecture software", 
    "free landing page builders", 
    "free pdf editor app", 
    "coreldraw software", 
    "microsoft apps for business", 
    "modern interior design", 
    "best video editing software for pc", 
    "decorating ideas", 
    "wall design ideas", 
    "wall painting design", 
    "free cad drawing software", 
    "erp cloud", 
    "microsoft access for mac", 
    "best video maker app", 
    "3d house builder", 
    "coreldraw for mac", 
    "art design", 
    "3d landscape design software free", 
    "interior design tools", 
    "enterprise project management software", 
    "brand logo creator", 
    "small house design", 
    "microsoft office desktop", 
    "product design software", 
    "online interior design tool", 
    "adobe app download", 
    "autocad software free download", 
    "kitchen design program", 
    "room design ideas", 
    "room interior design", 
    "adobe illustrator app", 
    "burberry logo", 
    "scandinavian interior design", 
    "room ideas", 
    "paisley print", 
    "coreldraw 2020", 
    "voice recording software", 
    "adobe software list", 
    "tshirt design software", 
    "excel software", 
    "adobe indesign price", 
    "free construction drawing software", 
    "free pdf software", 
    "best pdf software", 
    "drawing software for pc", 
    "master bedroom design", 
    "best drawing software", 
    "illustrator program", 
    "video capture software free", 
    "logo making software", 
    "ai adobe illustrator", 
    "digital poster maker", 
    "software to record screen and audio", 
    "paisley pattern", 
    "small bedroom design", 
    "3d home architect", 
    "adobe design software", 
    "billing software free download", 
    "buy adobe illustrator", 
    "2d cad software", 
    "adobe creative cloud free", 
    "file sharing software", 
    "best house design software", 
    "house plan drawing online free", 
    "3d house design free", 
    "autocad buy", 
    "3d graphic design", 
    "best free home design software", 
    "modern bed design", 
    "all adobe programs", 
    "adobe creative cloud all apps", 
    "free brand logo maker", 
    "house layout planner", 
    "canva alternatives", 
    "3d kitchen design free", 
    "autocad purchase", 
    "best list app", 
    "coreldraw x8", 
    "cad software for mac", 
    "electrical cad software", 
    "toilet design", 
    "best online logo maker", 
    "adobe photoshop and illustrator", 
    "company logo maker free", 
    "cool logo maker", 
    "drawing programs for pc", 
    "modern design", 
    "adobe drawing software", 
    "graphic design generator", 
    "best logo design app free", 
    "coreldraw technical suite", 
    "top mobile app development companies", 
    "ui ux design software", 
    "adobe indesign cost", 
    "home design programs", 
    "free floor plan design software", 
    "chair design", 
    "easy floor plan creator", 
    "balcony design", 
    "menu maker online", 
    "free web design templates", 
    "graphic software", 
    "new house design", 
    "adobe design suite", 
    "the best video editing app", 
    "cad software free download", 
    "best free design software", 
    "app design online", 
    "recording studio software", 
    "adobe illustrator software", 
    "coreldraw graphics suite 2020", 
    "almirah design", 
    "new home design", 
    "computer design programs", 
    "2d design software", 
    "adobe designer", 
    "adobe bundle", 
    "indesign price", 
    "3d house design software", 
    "youtube logo maker free", 
    "name tag design", 
    "false ceiling design for hall", 
    "best 3d home design software", 
    "coreldraw 2018", 
    "mandir design", 
    "editing software for pc", 
    "adobe cad", 
    "adobe illustrator and photoshop bundle", 
    "duplex house design", 
    "house design program", 
    "best interior design programs", 
    "2d drawing software free", 
    "engineering drawing software", 
    "best video editor software", 
    "adobe illustrator subscription", 
    "3d cabinet design software", 
    "menu card design", 
    "tv panel design", 
    "wall texture design", 
    "guo pei", 
    "adobe illustrator and photoshop", 
    "tommy hilfiger logo", 
    "best audio recording software", 
    "adobe illustrator for students", 
    "3d house maker", 
    "home colour design", 
    "best 3d interior design software", 
    "coreldraw price", 
    "room design online free", 
    "best cad software for beginners", 
    "video maker app download", 
    "best editing software for pc", 
    "visio desktop app", 
    "adobe cad software", 
    "small room design", 
    "best free logo maker app", 
    "3d packaging design online free", 
    "free exterior house design app", 
    "free kitchen cabinet design software", 
    "pdf editor software free download", 
    "fashion illustration", 
    "app mockup generator", 
    "pop design for hall", 
    "minimalism", 
    "graphic art software", 
    "home architect software", 
    "cad architecture", 
    "online house plan maker", 
    "virtual house design", 
    "adobe xd price", 
    "online logo maker free without watermark", 
    "coreldraw design", 
    "architectural drawing software free", 
    "home layout design free", 
    "bed design latest", 
    "interior design 3d modeling", 
    "house styles", 
    "frame design", 
    "mandir design for home", 
    "room colour design", 
    "autocad software download for pc", 
    "online banner maker free printable", 
    "house plan design online free", 
    "best 3d cad software", 
    "pdf to word converter software free download", 
    "drawing room design", 
    "best 3d house design software", 
    "microsoft office applications", 
    "kitchen planning software", 
    "simple bed design", 
    "online home designer", 
    "bag design", 
    "simple house design", 
    "t shirt mockup online", 
    "marble design", 
    "coreldraw graphics suite x7", 
    "pdf editor free software", 
    "textile design", 
    "house elevation design", 
    "3d home design software free download", 
    "best free house design software", 
    "all adobe software", 
    "home design app for pc", 
    "free cabinet drawing software", 
    "pop ceiling design", 
    "mockup generator free online", 
    "free music making apps", 
    "canva designer", 
    "pdf professional software", 
    "slogan design", 
    "3d interior design free", 
    "free electrical cad software", 
    "false ceiling design for bedroom", 
    "3d max online", 
    "coreldraw 2017", 
    "home design 3d for pc", 
    "bedroom ceiling design", 
    "zimyo hrms", 
    "led panel design", 
    "best digital drawing software", 
    "blueprint drawing online free", 
    "free architectural drafting software", 
    "html designer online", 
    "coach logo", 
    "video editing software for pc free download", 
    "autocad on mac", 
    "adobe drawing app", 
    "coreldraw graphics", 
    "ceiling design for hall", 
    "pvc ceiling design"
  ]
};
export default function Page() {
  return (
    <>
      <Page_container />
    </>
  );
}
