"use client";
import Footer from "@/components/Layout/Footer/Footer";
import Header from "@/components/Layout/Header/Header";
import Page_sup from "./Page_contant";
import dynamic from "next/dynamic";

export const metadata = {
  title: "bondify Crm",
  description: "Generated by create next app",
};

function Page() {

  return (
    <div className="page_hid">
      <Header />
      <Page_sup />
      <Footer />
    </div>
  );
}

export default dynamic(() => Promise.resolve(Page), { ssr: false });
