"use client";
import Footer from "@/components/Layout/Footer/Footer";
import Header from "@/components/Layout/Header/Header";
import Page_sup from "./Page_contant";
import { useEffect, useState } from "react";
import Contact from "@/components/Contact/Contact";
import dynamic from "next/dynamic";

export const metadata = {
  title: "Bondify Crm",
  description: "Generated by create next app",
};

function Page() {
  const [toggle, setToggle] = useState(false);

  const handleToggle = () => {
    setToggle(!toggle);
  };

  return (
    <div className="page_hid">
      <Header handleToggle={handleToggle} />
      <Page_sup />
      <Footer />
      <Contact
        handleToggle={handleToggle}
        toggle={toggle}
        setToggle={setToggle}
      />
    </div>
  );
}

export default dynamic(() => Promise.resolve(Page), { ssr: false });
