"use client"
import React from "react";
import Page_container from "./Page_sup/Page_container"
// export const metadata = {
//     title: "RD App",
//     description: "Generated by create next app",
//   };
  

export default function Page() {


  return (
    
    <>
        <Page_container />
    </>
  )
}
