"use client"
import Footer from '@/components/Layout/Footer/Footer'
import Header from '@/components/Layout/Header/Header'
import Page_sup from './Page_contant'
import Loading_page from '@/components/Loading_page/Loading_page'
import { useEffect, useState } from 'react'

export const metadata = {
    title: "CladCut",
    description: "Generated by create next app",
  };
  

export default function Page() {
    const [showTimer , setShowTimer] = useState(0)
  
    function handleTimer(){
      setShowTimer(showTimer + 1)
    }
  
    useEffect(()=>{
      if(showTimer < 2){
      setTimeout(handleTimer,1000)
      console.log('timer')
      }
    },[showTimer])

  return (
    
    <div className='page_hid'>
        {
      showTimer < 2 ? <Loading_page /> :
      <>
        <Header />
          <Page_sup />
        <Footer />
      </>
      }
    </div>
  )
}
